# Generated by Django 3.1.7 on 2021-08-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210812_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='user_response',
        ),
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
